coverage:
  range: 70..100
  round: down
  precision: 1
  ignore:
    - "tests/in_progress/*"
    - "tests/test_frames.py"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
