site_name: trivia-game
repo_url: https://github.com/bartczak-pa/trivia-game
site_url: https://bartczak-pa.github.io/trivia-game
site_description: Trivia Game
site_author: Pawel Bartczak
edit_uri: edit/main/docs/
repo_name: bartczak-pa/trivia-game
copyright: Maintained by <a href="https://bartczak-pa.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bartczak-pa/trivia-game
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/trivia-game

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
