import customtkinter as ctk

from trivia_game.view.frames.base_frame import BaseFrame

class BaseQuizFrame(BaseFrame):
    question_label: ctk.CTkLabel
    question_frame: ctk.CTkFrame

    def _setup_grid(self) -> None: ...
    def _create_widgets(self) -> None: ...
    def _create_question_frame(self) -> None: ...
    def _create_question_label(self) -> None: ...
    def _create_answer_buttons(self) -> None: ...
    def _handle_answer(self, answer: str) -> None: ...
    def display_question(self) -> None: ...
    def refresh(self) -> None: ...
    def _clear_previous_widgets(self) -> None: ...
    def _reset_and_continue(self) -> None: ...

class TrueFalseQuizFrame(BaseQuizFrame):
    def _setup_grid(self) -> None: ...
    def _create_widgets(self) -> None: ...
    def _create_answer_buttons(self) -> None: ...

class MultipleChoiceQuizFrame(BaseQuizFrame):
    def _setup_grid(self) -> None: ...
    def _create_widgets(self) -> None: ...
    def _create_answer_buttons(self) -> None: ...
