import customtkinter as ctk

from trivia_game.base_types import AppControllerProtocol

class ScoreboardFrame(ctk.CTkFrame):
    def __init__(self, parent: ctk.CTkFrame, controller: AppControllerProtocol) -> None: ...
    def _setup_grid(self) -> None: ...
    def _create_widgets(self) -> None: ...
    def load_scores(self) -> None: ...
    def _display_scores(self, scores: list[dict]) -> None: ...
    def _create_score_row(self, player: str, score: str, date: str, is_header: bool = False) -> None: ...
    def _display_no_scores(self) -> None: ...
    def _get_next_row(self) -> int: ...
    def _get_current_row(self) -> int: ...
    def _format_date(self, date_str: str) -> str: ...
    def refresh(self) -> None: ...
