from typing import Literal

import customtkinter as ctk

from trivia_game.base_types import AppControllerProtocol

class StartGameFrame(ctk.CTkFrame):
    category_var: ctk.StringVar
    difficulty_var: ctk.StringVar
    type_var: ctk.StringVar

    def __init__(self, parent: ctk.CTkFrame, controller: AppControllerProtocol) -> None: ...
    def _setup_grid(self) -> None: ...
    def _create_widgets(self) -> None: ...
    def _init_variables(self) -> None: ...
    def _create_option_menus(self) -> None: ...
    def _create_option_menu(self, label: str, variable: ctk.StringVar, values: list[str], row: int) -> None: ...
    def _create_buttons(self) -> None: ...
    def get_selected_values(
        self,
    ) -> tuple[str | None, Literal["easy", "medium", "hard"] | None, Literal["multiple", "boolean"] | None]: ...
    def _start_game(self) -> None: ...
    def set_categories(self, categories: list[str]) -> None: ...
